---
title: "Assignment 1: Introduction"
author: "Iman Byndloss"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have used RStudio (and at times, GitHub) in a couple of previous courses during undergrad. RStudio was also what I used to analyze the camara trap and climatic data involved in my undergraduate thesis.

2. Are there any components of the course about which you feel confident?

> Answer: I am confident on some of the basics of RStudio and GitHub, but in the past, I often had the help of a more experienced individual when I ran into a problem.

3. Are there any components of the course about which you feel apprehensive?

> Answer: It will be my first time working on a group project in RStudio, and I am unsure if we will be able to develop a project that we are all excited to be a part of. No matter the case, I am looking forward to learning more about data analytics! 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/ImanByndloss/EDE_Fall2024.git

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
